DATABASE_URL = "mongodb://localhost:27017/file_share"
USER_COLLECTION = "testuser"
FILES_COLLECTION = "testfiles"
AUTH_COLLECTION = "testauth"

MAX_FILE_SIZE = 300 * 1024 * 1024
DEFAULT_UPLOAD_FOLDER = "downloaded_files"
FILE_HASH_LENGTH = 10
ALLOWED_FILE_EXTENSIONS = ["pdf", "png"]

AUTH_TOKEN_LENGTH = 10

SECRET_KEY = "difenli3ilfaea2dkfj"
SESSION_ID_LENGTH = 10
MAX_SESSIONS = 3
